# Generated by Django 5.2.8 on 2025-12-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='введите имя студента')),
                ('third_name', models.CharField(blank=True, max_length=100, verbose_name='введите отчество')),
                ('age', models.PositiveIntegerField(default=17, verbose_name='введите возраст')),
                ('certificate', models.FileField(upload_to='documents/', verbose_name='загрузите аттестат')),
                ('ORT_test', models.URLField(verbose_name='загрузите результат ORT')),
                ('directions', models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('UX-UI', 'UX-UI'), ('Не определился(ась)', 'Не определился(ась)')], default='Backend', max_length=100, verbose_name='выберите направление')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'студента',
                'verbose_name_plural': 'студенты',
            },
        ),
    ]
