# Generated by Django 5.2.8 on 2025-11-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'verbose_name': 'новый блог', 'verbose_name_plural': 'новости об IT'},
        ),
        migrations.AlterField(
            model_name='newspost',
            name='url_news',
            field=models.URLField(blank=True, null=True, verbose_name='вставьте ссылку с YOUTUBE'),
        ),
    ]
