# Generated by Django 5.2.8 on 2025-12-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_newspost_options_alter_newspost_url_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(verbose_name='вставьте ссылки с картинок GOOGLE')),
            ],
            options={
                'verbose_name': 'картинку',
                'verbose_name_plural': 'картинки',
            },
        ),
    ]
