# Generated by Django 5.2.8 on 2025-12-02 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(choices=[('❤️', '❤️'), ('❤️❤️', '❤️❤️'), ('❤️❤️❤️', '❤️❤️❤️'), ('❤️❤️❤️❤️', '❤️❤️❤️❤️'), ('❤️❤️❤️❤️❤️', '❤️❤️❤️❤️❤️')], default='❤️❤️❤️❤️', max_length=100)),
                ('text', models.TextField(verbose_name='Напишите отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='blog.newspost')),
            ],
        ),
    ]
