# Generated by Django 6.0 on 2025-12-12 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_car', models.CharField(max_length=100, verbose_name='введите название машины')),
                ('name_driver', models.CharField(default='Иван', max_length=100, verbose_name='укажите имя водителя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NummerCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_car', models.CharField(default='--KG------', max_length=100, verbose_name='придумайте номер машины')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nummer_car', to='cars.car')),
            ],
        ),
    ]
